version: '3.8'

services:
  # Frontend (React)
  frontend:
    build:
      context: ./certs-view-client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Backend (Node.js)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    volumes:
      - ./server/logs:/app/logs

networks:
  app-network:
    driver: bridge

volumes:
  logs:
